# Generated by Django 5.1.6 on 2025-02-26 14:12

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMeta',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(max_length=128, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=128, verbose_name='菜单图标')),
                ('rank', models.IntegerField(default=999, verbose_name='菜单排序')),
                ('enter_animation', models.CharField(blank=True, max_length=128, verbose_name='进入动画')),
                ('leave_animation', models.CharField(blank=True, max_length=128, verbose_name='离开动画')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('parent_is_show', models.BooleanField(default=False, verbose_name='父级菜单是否显示')),
                ('is_keepalive', models.BooleanField(default=False, max_length=128, verbose_name='是否缓存页面')),
                ('fixed_tag', models.BooleanField(default=False, verbose_name='固定标签')),
                ('iframe_url', models.CharField(blank=True, max_length=128, verbose_name='iframe链接地址')),
                ('iframe_loading', models.BooleanField(default=True, verbose_name='iframe加载动画')),
                ('is_hidden_tag', models.BooleanField(default=True, verbose_name='隐藏标签名')),
                ('dynamic_level', models.IntegerField(default=0, verbose_name='动态路由等级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜单/权限表元数据',
                'verbose_name_plural': '菜单/权限表元数据',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('route_name', models.CharField(blank=True, max_length=128, verbose_name='路由名称/外链')),
                ('menu_type', models.SmallIntegerField(choices=[(0, '菜单'), (1, 'iframe'), (3, '外链'), (4, '按钮')], verbose_name='菜单类型')),
                ('code', models.CharField(blank=True, max_length=128, verbose_name='权限标识')),
                ('route_path', models.CharField(blank=True, max_length=255, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=255, verbose_name='组件路径')),
                ('redirect', models.CharField(blank=True, max_length=128, verbose_name='重定向地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu', verbose_name='上级菜单')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.menumeta', verbose_name='菜单元数据')),
            ],
            options={
                'verbose_name': '菜单/权限表',
                'verbose_name_plural': '菜单/权限表',
                'ordering': ('create_time',),
            },
        ),
    ]
