# Generated by Django 5.1.6 on 2025-02-24 17:49

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=128, verbose_name='菜单名称')),
                ('menu_type', models.SmallIntegerField(choices=[(0, '菜单'), (1, 'iframe'), (3, '外链'), (4, '按钮')], verbose_name='菜单类型')),
                ('router_name', models.CharField(blank=True, max_length=128, verbose_name='路由名称')),
                ('router_path', models.CharField(blank=True, max_length=128, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=128, verbose_name='组件路径')),
                ('rank', models.IntegerField(default=999, verbose_name='菜单排序')),
                ('router_redirect', models.CharField(blank=True, max_length=128, verbose_name='路由重定向地址')),
                ('icon', models.CharField(blank=True, max_length=128, verbose_name='菜单图标')),
                ('enter_animation', models.CharField(choices=[('bounce', 'bounce'), ('flash', 'flash'), ('pulse', 'pulse'), ('rubberBand', 'rubberBand')], default='bounce', max_length=128, verbose_name='进入动画')),
                ('leave_animation', models.CharField(choices=[('bounce', 'bounce'), ('flash', 'flash'), ('pulse', 'pulse'), ('rubberBand', 'rubberBand')], default='bounce', max_length=128, verbose_name='离开动画')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('parent_is_show', models.BooleanField(verbose_name='父级菜单是否显示')),
                ('cache_page', models.BooleanField(max_length=128, verbose_name='缓存页面')),
                ('fixed_tag', models.BooleanField(default=False, verbose_name='固定标签')),
                ('iframe', models.CharField(blank=True, max_length=128, verbose_name='iframe链接地址')),
                ('url', models.CharField(blank=True, max_length=128, verbose_name='外链地址')),
                ('code', models.CharField(blank=True, max_length=128, verbose_name='权限标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单/权限表',
                'verbose_name_plural': '菜单/权限表',
                'ordering': ('-rank', 'create_time'),
            },
        ),
    ]
