# Generated by Django 5.1.6 on 2025-02-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_menu', to='menu.menu', verbose_name='上级菜单'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='parent_is_show',
            field=models.BooleanField(default=True, verbose_name='父级菜单是否显示'),
        ),
    ]
