# Generated by Django 5.1.6 on 2025-02-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_parent_alter_menumeta_parent_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumeta',
            name='dynamic_level',
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='rank',
            field=models.IntegerField(default=99, verbose_name='菜单排序'),
        ),
    ]
