# Generated by Django 5.1.6 on 2025-02-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menumeta_dynamic_level_alter_menumeta_rank'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='system_menu',
        ),
        migrations.AlterModelTable(
            name='menumeta',
            table='system_menu_meta',
        ),
    ]
