# Generated by Django 5.1.6 on 2025-03-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumeta',
            name='is_hidden_tag',
            field=models.BooleanField(default=False, verbose_name='隐藏标签名'),
        ),
        migrations.AlterField(
            model_name='menumeta',
            name='is_keepalive',
            field=models.BooleanField(default=True, max_length=128, verbose_name='是否缓存页面'),
        ),
    ]
