# Generated by Django 5.1.6 on 2025-02-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_parent_alter_menumeta_parent_is_show'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(related_name='roles', related_query_name='role', to='menu.menu', verbose_name='菜单/权限'),
        ),
    ]
