# Generated by Django 5.1.6 on 2025-02-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_menus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='system_role',
        ),
    ]
