# Generated by Django 5.1.6 on 2025-03-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='parent_department',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_level',
        ),
    ]
