# Generated by Django 5.1.6 on 2025-03-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_parent_department_department_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_departments', to='department.department', verbose_name='上级部门'),
        ),
    ]
