# Generated by Django 5.1.6 on 2025-02-26 14:12

import apps.system.user.models
import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=128, verbose_name='姓名/昵称')),
                ('telephone', models.CharField(max_length=128, unique=True, verbose_name='电话号码')),
                ('avatar', models.CharField(blank=True, max_length=128, verbose_name='用户头像')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', related_query_name='department', to='department.department', verbose_name='所属部门')),
                ('roles', models.ManyToManyField(related_name='users', related_query_name='roles', to='role.role', verbose_name='用户角色')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
            managers=[
                ('objects', apps.system.user.models.UserManager()),
            ],
        ),
    ]
