# Generated by Django 5.1.6 on 2025-02-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='system_user',
        ),
    ]
