# Generated by Django 5.1.6 on 2025-02-19 17:37

import apps.system.sakura_auth.models
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SakuraUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=150, verbose_name='姓名/昵称')),
                ('telephone', models.CharField(max_length=150, unique=True, verbose_name='电话号码')),
                ('avatar', models.CharField(blank=True, max_length=150, verbose_name='用户头像')),
                ('email', models.CharField(blank=True, max_length=150, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
            managers=[
                ('objects', apps.system.sakura_auth.models.SakuraUserManager()),
            ],
        ),
    ]
